LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE       := PhysX
LOCAL_CPP_FEATURES := # rtti exceptions
LOCAL_ARM_NEON     := true # force NEON usage for all files

LOCAL_CPPFLAGS     := -O3 -fshort-wchar -ffast-math -fomit-frame-pointer -fpermissive -ffunction-sections -fdata-sections -fvisibility=hidden -ffriend-injection -fms-extensions -s -std=c++17 -Wno-invalid-offsetof -Wno-invalid-noreturn -DPX_PHYSX_STATIC_LIB -DPX_COOKING -DNDEBUG \
	-I../physx/include \
	-I../physx/include/characterkinematic \
	-I../physx/include/collision \
	-I../physx/include/common \
	-I../physx/include/cooking \
	-I../physx/include/cudamanager \
	-I../physx/include/extensions \
	-I../physx/include/filebuf \
	-I../physx/include/foundation \
	-I../physx/include/geometry \
	-I../physx/include/geomutils \
	-I../physx/include/gpu \
	-I../physx/include/pvd \
	-I../physx/include/solver \
	-I../physx/include/task \
	-I../physx/include/vehicle \
	-I../physx/source/common/include \
	-I../physx/source/common/src \
	-I../physx/source/fastxml/include \
	-I../physx/source/filebuf/include \
	-I../physx/source/foundation/include \
	-I../physx/source/foundation/include/unix \
	-I../physx/source/foundation/include/unix/neon \
	-I../physx/source/foundation/include/unix/sse2 \
	-I../physx/source/geomutils/include \
	-I../physx/source/geomutils/src \
	-I../physx/source/geomutils/src/ccd \
	-I../physx/source/geomutils/src/common \
	-I../physx/source/geomutils/src/contact \
	-I../physx/source/geomutils/src/convex \
	-I../physx/source/geomutils/src/distance \
	-I../physx/source/geomutils/src/gjk \
	-I../physx/source/geomutils/src/hf \
	-I../physx/source/geomutils/src/intersection \
	-I../physx/source/geomutils/src/mesh \
	-I../physx/source/geomutils/src/pcm \
	-I../physx/source/geomutils/src/sweep \
	-I../physx/source/lowlevel/api/include \
	-I../physx/source/lowlevel/common/include \
	-I../physx/source/lowlevel/common/include/collision \
	-I../physx/source/lowlevel/common/include/pipeline \
	-I../physx/source/lowlevel/common/include/utils \
	-I../physx/source/lowlevel/software/include \
	-I../physx/source/lowlevelaabb/include \
	-I../physx/source/lowlevelaabb/src \
	-I../physx/source/lowleveldynamics/include \
	-I../physx/source/lowleveldynamics/src \
	-I../physx/source/physx/src \
	-I../physx/source/physx/src/buffering \
	-I../physx/source/physx/src/device \
	-I../physx/source/physxcharacterkinematic/src \
	-I../physx/source/physxcooking/src \
	-I../physx/source/physxcooking/src/convex \
	-I../physx/source/physxcooking/src/mesh \
	-I../physx/source/physxextensions/src \
	-I../physx/source/physxextensions/src/serialization \
	-I../physx/source/physxextensions/src/serialization/Binary \
	-I../physx/source/physxextensions/src/serialization/File \
	-I../physx/source/physxextensions/src/serialization/Xml \
	-I../physx/source/physxgpu/include \
	-I../physx/source/physxmetadata/core/include \
	-I../physx/source/physxmetadata/extensions/include \
	-I../physx/source/physxvehicle/src \
	-I../physx/source/physxvehicle/src/physxmetadata/include \
	-I../physx/source/pvd/include \
	-I../physx/source/scenequery/include \
	-I../physx/source/scenequery/src \
	-I../physx/source/simulationcontroller/include \
	-I../physx/source/simulationcontroller/src \
	-I../physx/tools/physxmetadatagenerator \
	-I../pxshared/include \
	-I../pxshared/include/foundation \
	-I../pxshared/include/foundation/unix

LOCAL_SRC_FILES := \
	../../physx/source/common/src/CmCollection.cpp \
	../../physx/source/common/src/CmMathUtils.cpp \
	../../physx/source/common/src/CmPtrTable.cpp \
	../../physx/source/common/src/CmRadixSort.cpp \
	../../physx/source/common/src/CmRadixSortBuffered.cpp \
	../../physx/source/common/src/CmRenderOutput.cpp \
	../../physx/source/common/src/CmVisualization.cpp \
	../../physx/source/fastxml/src/PsFastXml.cpp \
	../../physx/source/foundation/src/PsAllocator.cpp \
	../../physx/source/foundation/src/PsAssert.cpp \
	../../physx/source/foundation/src/PsFoundation.cpp \
	../../physx/source/foundation/src/PsMathUtils.cpp \
	../../physx/source/foundation/src/PsString.cpp \
	../../physx/source/foundation/src/PsTempAllocator.cpp \
	../../physx/source/foundation/src/PsUtilities.cpp \
	../../physx/source/foundation/src/unix/PsUnixAtomic.cpp \
	../../physx/source/foundation/src/unix/PsUnixCpu.cpp \
	../../physx/source/foundation/src/unix/PsUnixFPU.cpp \
	../../physx/source/foundation/src/unix/PsUnixMutex.cpp \
	../../physx/source/foundation/src/unix/PsUnixPrintString.cpp \
	../../physx/source/foundation/src/unix/PsUnixSList.cpp \
	../../physx/source/foundation/src/unix/PsUnixSocket.cpp \
	../../physx/source/foundation/src/unix/PsUnixSync.cpp \
	../../physx/source/foundation/src/unix/PsUnixThread.cpp \
	../../physx/source/foundation/src/unix/PsUnixTime.cpp \
	../../physx/source/geomutils/src/ccd/GuCCDSweepConvexMesh.cpp \
	../../physx/source/geomutils/src/ccd/GuCCDSweepPrimitives.cpp \
	../../physx/source/geomutils/src/common/GuBarycentricCoordinates.cpp \
	../../physx/source/geomutils/src/common/GuSeparatingAxes.cpp \
	../../physx/source/geomutils/src/contact/GuContactBoxBox.cpp \
	../../physx/source/geomutils/src/contact/GuContactCapsuleBox.cpp \
	../../physx/source/geomutils/src/contact/GuContactCapsuleCapsule.cpp \
	../../physx/source/geomutils/src/contact/GuContactCapsuleConvex.cpp \
	../../physx/source/geomutils/src/contact/GuContactCapsuleMesh.cpp \
	../../physx/source/geomutils/src/contact/GuContactConvexConvex.cpp \
	../../physx/source/geomutils/src/contact/GuContactConvexMesh.cpp \
	../../physx/source/geomutils/src/contact/GuContactPlaneBox.cpp \
	../../physx/source/geomutils/src/contact/GuContactPlaneCapsule.cpp \
	../../physx/source/geomutils/src/contact/GuContactPlaneConvex.cpp \
	../../physx/source/geomutils/src/contact/GuContactPolygonPolygon.cpp \
	../../physx/source/geomutils/src/contact/GuContactSphereBox.cpp \
	../../physx/source/geomutils/src/contact/GuContactSphereCapsule.cpp \
	../../physx/source/geomutils/src/contact/GuContactSphereMesh.cpp \
	../../physx/source/geomutils/src/contact/GuContactSpherePlane.cpp \
	../../physx/source/geomutils/src/contact/GuContactSphereSphere.cpp \
	../../physx/source/geomutils/src/contact/GuFeatureCode.cpp \
	../../physx/source/geomutils/src/convex/GuBigConvexData.cpp \
	../../physx/source/geomutils/src/convex/GuConvexHelper.cpp \
	../../physx/source/geomutils/src/convex/GuConvexMesh.cpp \
	../../physx/source/geomutils/src/convex/GuConvexSupportTable.cpp \
	../../physx/source/geomutils/src/convex/GuConvexUtilsInternal.cpp \
	../../physx/source/geomutils/src/convex/GuHillClimbing.cpp \
	../../physx/source/geomutils/src/convex/GuShapeConvex.cpp \
	../../physx/source/geomutils/src/distance/GuDistancePointBox.cpp \
	../../physx/source/geomutils/src/distance/GuDistancePointTriangle.cpp \
	../../physx/source/geomutils/src/distance/GuDistanceSegmentBox.cpp \
	../../physx/source/geomutils/src/distance/GuDistanceSegmentSegment.cpp \
	../../physx/source/geomutils/src/distance/GuDistanceSegmentTriangle.cpp \
	../../physx/source/geomutils/src/gjk/GuEPA.cpp \
	../../physx/source/geomutils/src/gjk/GuGJKSimplex.cpp \
	../../physx/source/geomutils/src/gjk/GuGJKTest.cpp \
	../../physx/source/geomutils/src/GuAABBTreeBuild.cpp \
	../../physx/source/geomutils/src/GuBounds.cpp \
	../../physx/source/geomutils/src/GuBox.cpp \
	../../physx/source/geomutils/src/GuBVHStructure.cpp \
	../../physx/source/geomutils/src/GuCapsule.cpp \
	../../physx/source/geomutils/src/GuCCTSweepTests.cpp \
	../../physx/source/geomutils/src/GuGeometryQuery.cpp \
	../../physx/source/geomutils/src/GuGeometryUnion.cpp \
	../../physx/source/geomutils/src/GuInternal.cpp \
	../../physx/source/geomutils/src/GuMeshFactory.cpp \
	../../physx/source/geomutils/src/GuMetaData.cpp \
	../../physx/source/geomutils/src/GuMTD.cpp \
	../../physx/source/geomutils/src/GuOverlapTests.cpp \
	../../physx/source/geomutils/src/GuRaycastTests.cpp \
	../../physx/source/geomutils/src/GuSerialize.cpp \
	../../physx/source/geomutils/src/GuSweepMTD.cpp \
	../../physx/source/geomutils/src/GuSweepSharedTests.cpp \
	../../physx/source/geomutils/src/GuSweepTests.cpp \
	../../physx/source/geomutils/src/hf/GuHeightField.cpp \
	../../physx/source/geomutils/src/hf/GuHeightFieldUtil.cpp \
	../../physx/source/geomutils/src/hf/GuOverlapTestsHF.cpp \
	../../physx/source/geomutils/src/hf/GuSweepsHF.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionBoxBox.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionCapsuleTriangle.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionEdgeEdge.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionRayBox.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionRayCapsule.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionRaySphere.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionSphereBox.cpp \
	../../physx/source/geomutils/src/intersection/GuIntersectionTriangleBox.cpp \
	../../physx/source/geomutils/src/mesh/GuBV32.cpp \
	../../physx/source/geomutils/src/mesh/GuBV32Build.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4Build.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_AABBSweep.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_BoxOverlap.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_CapsuleSweep.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_CapsuleSweepAA.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_OBBSweep.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_Raycast.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_SphereOverlap.cpp \
	../../physx/source/geomutils/src/mesh/GuBV4_SphereSweep.cpp \
	../../physx/source/geomutils/src/mesh/GuMeshQuery.cpp \
	../../physx/source/geomutils/src/mesh/GuMidphaseBV4.cpp \
	../../physx/source/geomutils/src/mesh/GuMidphaseRTree.cpp \
	../../physx/source/geomutils/src/mesh/GuOverlapTestsMesh.cpp \
	../../physx/source/geomutils/src/mesh/GuRTree.cpp \
	../../physx/source/geomutils/src/mesh/GuRTreeQueries.cpp \
	../../physx/source/geomutils/src/mesh/GuSweepsMesh.cpp \
	../../physx/source/geomutils/src/mesh/GuTriangleMesh.cpp \
	../../physx/source/geomutils/src/mesh/GuTriangleMeshBV4.cpp \
	../../physx/source/geomutils/src/mesh/GuTriangleMeshRTree.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactBoxBox.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactBoxConvex.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactCapsuleBox.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactCapsuleCapsule.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactCapsuleConvex.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactCapsuleHeightField.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactCapsuleMesh.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactConvexCommon.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactConvexConvex.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactConvexHeightField.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactConvexMesh.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactGenBoxConvex.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactGenSphereCapsule.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactPlaneBox.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactPlaneCapsule.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactPlaneConvex.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactSphereBox.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactSphereCapsule.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactSphereConvex.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactSphereHeightField.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactSphereMesh.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactSpherePlane.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMContactSphereSphere.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMShapeConvex.cpp \
	../../physx/source/geomutils/src/pcm/GuPCMTriangleContactGen.cpp \
	../../physx/source/geomutils/src/pcm/GuPersistentContactManifold.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepBoxBox.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepBoxSphere.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepBoxTriangle_FeatureBased.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepBoxTriangle_SAT.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepCapsuleBox.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepCapsuleCapsule.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepCapsuleTriangle.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepSphereCapsule.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepSphereSphere.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepSphereTriangle.cpp \
	../../physx/source/geomutils/src/sweep/GuSweepTriangleUtils.cpp \
	../../physx/source/immediatemode/src/NpImmediateMode.cpp \
	../../physx/source/lowlevel/api/src/px_globals.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcContactCache.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcContactMethodImpl.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcMaterialHeightField.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcMaterialMesh.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcMaterialMethodImpl.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcMaterialShape.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcNpBatch.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcNpCacheStreamPair.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcNpContactPrepShared.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcNpMemBlockPool.cpp \
	../../physx/source/lowlevel/common/src/pipeline/PxcNpThreadContext.cpp \
	../../physx/source/lowlevel/software/src/PxsCCD.cpp \
	../../physx/source/lowlevel/software/src/PxsContactManager.cpp \
	../../physx/source/lowlevel/software/src/PxsContext.cpp \
	../../physx/source/lowlevel/software/src/PxsDefaultMemoryManager.cpp \
	../../physx/source/lowlevel/software/src/PxsIslandSim.cpp \
	../../physx/source/lowlevel/software/src/PxsMaterialCombiner.cpp \
	../../physx/source/lowlevel/software/src/PxsNphaseImplementationContext.cpp \
	../../physx/source/lowlevel/software/src/PxsSimpleIslandManager.cpp \
	../../physx/source/lowlevelaabb/src/BpAABBManager.cpp \
	../../physx/source/lowlevelaabb/src/BpBroadPhase.cpp \
	../../physx/source/lowlevelaabb/src/BpBroadPhaseABP.cpp \
	../../physx/source/lowlevelaabb/src/BpBroadPhaseMBP.cpp \
	../../physx/source/lowlevelaabb/src/BpBroadPhaseSap.cpp \
	../../physx/source/lowlevelaabb/src/BpBroadPhaseSapAux.cpp \
	../../physx/source/lowlevelaabb/src/BpBroadPhaseShared.cpp \
	../../physx/source/lowlevelaabb/src/BpMBPTasks.cpp \
	../../physx/source/lowlevelaabb/src/BpSAPTasks.cpp \
	../../physx/source/lowleveldynamics/src/DyArticulation.cpp \
	../../physx/source/lowleveldynamics/src/DyArticulationContactPrep.cpp \
	../../physx/source/lowleveldynamics/src/DyArticulationContactPrepPF.cpp \
	../../physx/source/lowleveldynamics/src/DyArticulationHelper.cpp \
	../../physx/source/lowleveldynamics/src/DyArticulationScalar.cpp \
	../../physx/source/lowleveldynamics/src/DyArticulationSIMD.cpp \
	../../physx/source/lowleveldynamics/src/DyConstraintPartition.cpp \
	../../physx/source/lowleveldynamics/src/DyConstraintSetup.cpp \
	../../physx/source/lowleveldynamics/src/DyConstraintSetupBlock.cpp \
	../../physx/source/lowleveldynamics/src/DyContactPrep.cpp \
	../../physx/source/lowleveldynamics/src/DyContactPrep4.cpp \
	../../physx/source/lowleveldynamics/src/DyContactPrep4PF.cpp \
	../../physx/source/lowleveldynamics/src/DyContactPrepPF.cpp \
	../../physx/source/lowleveldynamics/src/DyDynamics.cpp \
	../../physx/source/lowleveldynamics/src/DyFeatherstoneArticulation.cpp \
	../../physx/source/lowleveldynamics/src/DyFeatherstoneForwardDynamic.cpp \
	../../physx/source/lowleveldynamics/src/DyFeatherstoneInverseDynamic.cpp \
	../../physx/source/lowleveldynamics/src/DyFrictionCorrelation.cpp \
	../../physx/source/lowleveldynamics/src/DyRigidBodyToSolverBody.cpp \
	../../physx/source/lowleveldynamics/src/DySolverConstraints.cpp \
	../../physx/source/lowleveldynamics/src/DySolverConstraintsBlock.cpp \
	../../physx/source/lowleveldynamics/src/DySolverControl.cpp \
	../../physx/source/lowleveldynamics/src/DySolverControlPF.cpp \
	../../physx/source/lowleveldynamics/src/DySolverPFConstraints.cpp \
	../../physx/source/lowleveldynamics/src/DySolverPFConstraintsBlock.cpp \
	../../physx/source/lowleveldynamics/src/DyTGSContactPrep.cpp \
	../../physx/source/lowleveldynamics/src/DyTGSContactPrepBlock.cpp \
	../../physx/source/lowleveldynamics/src/DyTGSDynamics.cpp \
	../../physx/source/lowleveldynamics/src/DyThreadContext.cpp \
	../../physx/source/lowleveldynamics/src/DyThresholdTable.cpp \
	../../physx/source/physx/src/buffering/ScbActor.cpp \
	../../physx/source/physx/src/buffering/ScbAggregate.cpp \
	../../physx/source/physx/src/buffering/ScbBase.cpp \
	../../physx/source/physx/src/buffering/ScbMetaData.cpp \
	../../physx/source/physx/src/buffering/ScbScene.cpp \
	../../physx/source/physx/src/buffering/ScbScenePvdClient.cpp \
	../../physx/source/physx/src/buffering/ScbShape.cpp \
	../../physx/source/physx/src/device/linux/PhysXIndicatorLinux.cpp \
	../../physx/source/physx/src/gpu/PxGpu.cpp \
	../../physx/source/physx/src/gpu/PxPhysXGpuModuleLoader.cpp \
	../../physx/source/physx/src/NpActor.cpp \
	../../physx/source/physx/src/NpAggregate.cpp \
	../../physx/source/physx/src/NpArticulation.cpp \
	../../physx/source/physx/src/NpArticulationJoint.cpp \
	../../physx/source/physx/src/NpArticulationJointReducedCoordinate.cpp \
	../../physx/source/physx/src/NpArticulationLink.cpp \
	../../physx/source/physx/src/NpArticulationReducedCoordinate.cpp \
	../../physx/source/physx/src/NpBatchQuery.cpp \
	../../physx/source/physx/src/NpConstraint.cpp \
	../../physx/source/physx/src/NpFactory.cpp \
	../../physx/source/physx/src/NpMaterial.cpp \
	../../physx/source/physx/src/NpMetaData.cpp \
	../../physx/source/physx/src/NpPhysics.cpp \
	../../physx/source/physx/src/NpPvdSceneQueryCollector.cpp \
	../../physx/source/physx/src/NpReadCheck.cpp \
	../../physx/source/physx/src/NpRigidDynamic.cpp \
	../../physx/source/physx/src/NpRigidStatic.cpp \
	../../physx/source/physx/src/NpScene.cpp \
	../../physx/source/physx/src/NpSceneQueries.cpp \
	../../physx/source/physx/src/NpSerializerAdapter.cpp \
	../../physx/source/physx/src/NpShape.cpp \
	../../physx/source/physx/src/NpShapeManager.cpp \
	../../physx/source/physx/src/NpWriteCheck.cpp \
	../../physx/source/physx/src/PvdMetaDataPvdBinding.cpp \
	../../physx/source/physx/src/PvdPhysicsClient.cpp \
	../../physx/source/physxcharacterkinematic/src/CctBoxController.cpp \
	../../physx/source/physxcharacterkinematic/src/CctCapsuleController.cpp \
	../../physx/source/physxcharacterkinematic/src/CctCharacterController.cpp \
	../../physx/source/physxcharacterkinematic/src/CctCharacterControllerCallbacks.cpp \
	../../physx/source/physxcharacterkinematic/src/CctCharacterControllerManager.cpp \
	../../physx/source/physxcharacterkinematic/src/CctController.cpp \
	../../physx/source/physxcharacterkinematic/src/CctObstacleContext.cpp \
	../../physx/source/physxcharacterkinematic/src/CctSweptBox.cpp \
	../../physx/source/physxcharacterkinematic/src/CctSweptCapsule.cpp \
	../../physx/source/physxcharacterkinematic/src/CctSweptVolume.cpp \
	../../physx/source/physxcooking/src/Adjacencies.cpp \
	../../physx/source/physxcooking/src/BVHStructureBuilder.cpp \
	../../physx/source/physxcooking/src/convex/BigConvexDataBuilder.cpp \
	../../physx/source/physxcooking/src/convex/ConvexHullBuilder.cpp \
	../../physx/source/physxcooking/src/convex/ConvexHullLib.cpp \
	../../physx/source/physxcooking/src/convex/ConvexHullUtils.cpp \
	../../physx/source/physxcooking/src/convex/ConvexMeshBuilder.cpp \
	../../physx/source/physxcooking/src/convex/ConvexPolygonsBuilder.cpp \
	../../physx/source/physxcooking/src/convex/QuickHullConvexHullLib.cpp \
	../../physx/source/physxcooking/src/convex/VolumeIntegration.cpp \
	../../physx/source/physxcooking/src/Cooking.cpp \
	../../physx/source/physxcooking/src/CookingUtils.cpp \
	../../physx/source/physxcooking/src/EdgeList.cpp \
	../../physx/source/physxcooking/src/mesh/GrbTriangleMeshCooking.cpp \
	../../physx/source/physxcooking/src/mesh/HeightFieldCooking.cpp \
	../../physx/source/physxcooking/src/mesh/MeshBuilder.cpp \
	../../physx/source/physxcooking/src/mesh/RTreeCooking.cpp \
	../../physx/source/physxcooking/src/mesh/TriangleMeshBuilder.cpp \
	../../physx/source/physxcooking/src/MeshCleaner.cpp \
	../../physx/source/physxcooking/src/Quantizer.cpp \
	../../physx/source/physxextensions/src/ExtBroadPhase.cpp \
	../../physx/source/physxextensions/src/ExtCollection.cpp \
	../../physx/source/physxextensions/src/ExtContactJoint.cpp \
	../../physx/source/physxextensions/src/ExtConvexMeshExt.cpp \
	../../physx/source/physxextensions/src/ExtCpuWorkerThread.cpp \
	../../physx/source/physxextensions/src/ExtD6Joint.cpp \
	../../physx/source/physxextensions/src/ExtD6JointCreate.cpp \
	../../physx/source/physxextensions/src/ExtDefaultCpuDispatcher.cpp \
	../../physx/source/physxextensions/src/ExtDefaultErrorCallback.cpp \
	../../physx/source/physxextensions/src/ExtDefaultSimulationFilterShader.cpp \
	../../physx/source/physxextensions/src/ExtDefaultStreams.cpp \
	../../physx/source/physxextensions/src/ExtDistanceJoint.cpp \
	../../physx/source/physxextensions/src/ExtExtensions.cpp \
	../../physx/source/physxextensions/src/ExtFixedJoint.cpp \
	../../physx/source/physxextensions/src/ExtJoint.cpp \
	../../physx/source/physxextensions/src/ExtMetaData.cpp \
	../../physx/source/physxextensions/src/ExtPrismaticJoint.cpp \
	../../physx/source/physxextensions/src/ExtPvd.cpp \
	../../physx/source/physxextensions/src/ExtPxStringTable.cpp \
	../../physx/source/physxextensions/src/ExtRaycastCCD.cpp \
	../../physx/source/physxextensions/src/ExtRevoluteJoint.cpp \
	../../physx/source/physxextensions/src/ExtRigidActorExt.cpp \
	../../physx/source/physxextensions/src/ExtRigidBodyExt.cpp \
	../../physx/source/physxextensions/src/ExtSceneQueryExt.cpp \
	../../physx/source/physxextensions/src/ExtSimpleFactory.cpp \
	../../physx/source/physxextensions/src/ExtSmoothNormals.cpp \
	../../physx/source/physxextensions/src/ExtSphericalJoint.cpp \
	../../physx/source/physxextensions/src/ExtTriangleMeshExt.cpp \
	../../physx/source/physxmetadata/core/src/PxAutoGeneratedMetaDataObjects.cpp \
	../../physx/source/physxmetadata/core/src/PxMetaDataObjects.cpp \
	../../physx/source/physxmetadata/extensions/src/PxExtensionAutoGeneratedMetaDataObjects.cpp \
	../../physx/source/physxvehicle/src/physxmetadata/src/PxVehicleAutoGeneratedMetaDataObjects.cpp \
	../../physx/source/physxvehicle/src/physxmetadata/src/PxVehicleMetaDataObjects.cpp \
	../../physx/source/physxvehicle/src/PxVehicleComponents.cpp \
	../../physx/source/physxvehicle/src/PxVehicleDrive.cpp \
	../../physx/source/physxvehicle/src/PxVehicleDrive4W.cpp \
	../../physx/source/physxvehicle/src/PxVehicleDriveNW.cpp \
	../../physx/source/physxvehicle/src/PxVehicleDriveTank.cpp \
	../../physx/source/physxvehicle/src/PxVehicleMetaData.cpp \
	../../physx/source/physxvehicle/src/PxVehicleNoDrive.cpp \
	../../physx/source/physxvehicle/src/PxVehicleSDK.cpp \
	../../physx/source/physxvehicle/src/PxVehicleSerialization.cpp \
	../../physx/source/physxvehicle/src/PxVehicleSuspWheelTire4.cpp \
	../../physx/source/physxvehicle/src/PxVehicleTireFriction.cpp \
	../../physx/source/physxvehicle/src/PxVehicleUpdate.cpp \
	../../physx/source/physxvehicle/src/PxVehicleWheels.cpp \
	../../physx/source/physxvehicle/src/VehicleUtilControl.cpp \
	../../physx/source/physxvehicle/src/VehicleUtilSetup.cpp \
	../../physx/source/physxvehicle/src/VehicleUtilTelemetry.cpp \
	../../physx/source/scenequery/src/SqAABBPruner.cpp \
	../../physx/source/scenequery/src/SqAABBTree.cpp \
	../../physx/source/scenequery/src/SqAABBTreeUpdateMap.cpp \
	../../physx/source/scenequery/src/SqBounds.cpp \
	../../physx/source/scenequery/src/SqBucketPruner.cpp \
	../../physx/source/scenequery/src/SqCompoundPruner.cpp \
	../../physx/source/scenequery/src/SqCompoundPruningPool.cpp \
	../../physx/source/scenequery/src/SqExtendedBucketPruner.cpp \
	../../physx/source/scenequery/src/SqIncrementalAABBPruner.cpp \
	../../physx/source/scenequery/src/SqIncrementalAABBPrunerCore.cpp \
	../../physx/source/scenequery/src/SqIncrementalAABBTree.cpp \
	../../physx/source/scenequery/src/SqMetaData.cpp \
	../../physx/source/scenequery/src/SqPruningPool.cpp \
	../../physx/source/scenequery/src/SqPruningStructure.cpp \
	../../physx/source/scenequery/src/SqSceneQueryManager.cpp \
	../../physx/source/simulationcontroller/src/ScActorCore.cpp \
	../../physx/source/simulationcontroller/src/ScActorSim.cpp \
	../../physx/source/simulationcontroller/src/ScArticulationCore.cpp \
	../../physx/source/simulationcontroller/src/ScArticulationJointCore.cpp \
	../../physx/source/simulationcontroller/src/ScArticulationJointSim.cpp \
	../../physx/source/simulationcontroller/src/ScArticulationSim.cpp \
	../../physx/source/simulationcontroller/src/ScBodyCore.cpp \
	../../physx/source/simulationcontroller/src/ScBodySim.cpp \
	../../physx/source/simulationcontroller/src/ScConstraintCore.cpp \
	../../physx/source/simulationcontroller/src/ScConstraintGroupNode.cpp \
	../../physx/source/simulationcontroller/src/ScConstraintInteraction.cpp \
	../../physx/source/simulationcontroller/src/ScConstraintProjectionManager.cpp \
	../../physx/source/simulationcontroller/src/ScConstraintProjectionTree.cpp \
	../../physx/source/simulationcontroller/src/ScConstraintSim.cpp \
	../../physx/source/simulationcontroller/src/ScElementInteractionMarker.cpp \
	../../physx/source/simulationcontroller/src/ScElementSim.cpp \
	../../physx/source/simulationcontroller/src/ScInteraction.cpp \
	../../physx/source/simulationcontroller/src/ScIterators.cpp \
	../../physx/source/simulationcontroller/src/ScMetaData.cpp \
	../../physx/source/simulationcontroller/src/ScNPhaseCore.cpp \
	../../physx/source/simulationcontroller/src/ScPhysics.cpp \
	../../physx/source/simulationcontroller/src/ScRigidCore.cpp \
	../../physx/source/simulationcontroller/src/ScRigidSim.cpp \
	../../physx/source/simulationcontroller/src/ScScene.cpp \
	../../physx/source/simulationcontroller/src/ScShapeCore.cpp \
	../../physx/source/simulationcontroller/src/ScShapeInteraction.cpp \
	../../physx/source/simulationcontroller/src/ScShapeSim.cpp \
	../../physx/source/simulationcontroller/src/ScSimStats.cpp \
	../../physx/source/simulationcontroller/src/ScSimulationController.cpp \
	../../physx/source/simulationcontroller/src/ScSqBoundsManager.cpp \
	../../physx/source/simulationcontroller/src/ScStaticCore.cpp \
	../../physx/source/simulationcontroller/src/ScTriggerInteraction.cpp \
	../../physx/source/task/src/TaskManager.cpp

include $(BUILD_STATIC_LIBRARY)
